kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: machine-learning
featureGates:
  "GracefulNodeShutdown": true
  "ComponentSLIs": true
  "SidecarContainers": true
# networking:
  # We will use eBPF for CNI
  # https://docs.cilium.io/en/stable/installation/kind/
  # disableDefaultCNI: true
  # The default Pod and Service subnet ranges used by kind.
  # podSubnet: "10.244.0.0/16"
  # serviceSubnetL: "10.96.0.0/12"
  # In case these interfere with local networks (think other clusters),
  # we can change them.
  # podSubnet: "10.244.0.0/16"
  # serviceSubnet: "10.96.0.0/12"
